### ISSUE TITLE
Missing gds and lef files

### ISSUE THREAD

**Issue by vijayank88** [nguyendao-uom/ICESOC#3]
Hi @nguyendao-uom 
Can you please update your repo as per `macro.cfg` with all required `gds` and `lef` files in respective repo directory.

As its is part of mpw shuttle, google wants repo to be clean and executable as per `openlane/user_project_wrapper/config.tcl`

Thanks.

**Comment by nguyendao-uom** [comment]
Hi @vijayank88, we used Innovus for this hardening, so no macro.cfg was used.
Cheers.

**Comment by vijayank88** [comment]
@nguyendao-uom 
Thanks for update. Then https://github.com/nguyendao-uom/ICESOC/blob/2b19cba8937e563f98d2f28680a1ed45f5b0fc97/openlane/user_project_wrapper/config.tcl#L62 this is not valid and tested with `openlane`?

**Comment by nguyendao-uom** [comment]
Ahh, sorry, I mean we hardened the eFPGA_CPU_top by Innovus. I will upload the eFPGA_CPU_top.gds, with that you can run `make user_project_wrapper`.
